baseURL: "https://a-burigana.github.io" 
title: Alessandro Burigana
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        # - name: Books
        #   url: books/
        #   weight: 5 
        - name: Papers
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Archive
          url: archive/
          weight: 3 
        - name: Tags
          url: tags/
          weight: 4
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 6

params:
    description: "I am an Assistant Researcher in Computer Science at the Free University of Bolzano, Italy. My research focuses mostly on Epistemic Planning, Knowledge Representation and Reasoning and Multi-Agent Systems."
    author: Alessandro Burigana
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","projects","archive"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alessandro Burigana
          subtitle: "I am an Assistant Researcher in Computer Science at the Free University of Bolzano, Italy. My research focuses mostly on Epistemic Planning, Knowledge Representation and Reasoning and Multi-Agent Systems."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            - name: Archive
              url: archive/
            - name: Tags
              url: tags/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:alessandro.burigana@unibz.it
        # - name: Zoom
        #   url: https://www.zoom.us/my/igelfeld
        - name: Location
          url: location/
        # - name: Office Hours
        #   url: officehours/
        - name: ORCID
          url: https://orcid.org/0000-0002-9977-6735
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=FyTN_iEAAAAJ
        - name: dblp
          url: https://dblp.org/pid/266/4562.html
        - name: GitHub
          url: https://github.com/a-burigana
        - name: LinkedIn
          url: https://www.linkedin.com/in/alessandro-burigana-96a5aaaa/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alessandro Burigana"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
